package com.wwg.vo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * @author wuwei
 */
public class ManageAccount extends BaseVersionModel implements Serializable {

    private static final long serialVersionUID = 3092235640168826490L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jf_manage_account.account_no
     *
     * @mbggenerated Tue Aug 27 10:37:08 CST 2019
     */
    private String accountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jf_manage_account.cre_company_no
     *
     * @mbggenerated Tue Aug 27 10:37:08 CST 2019
     */
    private String creCompanyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jf_manage_account.account_name
     *
     * @mbggenerated Tue Aug 27 10:37:08 CST 2019
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jf_manage_account.account_type
     *
     * @mbggenerated Tue Aug 27 10:37:08 CST 2019
     */
    private String accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jf_manage_account.remaining_amount
     *
     * @mbggenerated Tue Aug 27 10:37:08 CST 2019
     */
    private BigDecimal remainingAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jf_manage_account.status
     *
     * @mbggenerated Tue Aug 27 10:37:08 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jf_manage_account.latest_trading_date
     *
     * @mbggenerated Tue Aug 27 10:37:08 CST 2019
     */
    private Date latestTradingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jf_manage_account.latest_trading_no
     *
     * @mbggenerated Tue Aug 27 10:37:08 CST 2019
     */
    private String latestTradingNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jf_manage_account.latest_operator
     *
     * @mbggenerated Tue Aug 27 10:37:08 CST 2019
     */
    private String latestOperator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jf_manage_account.account_no
     *
     * @return the value of jf_manage_account.account_no
     *
     * @mbggenerated Tue Aug 27 10:37:08 CST 2019
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jf_manage_account.account_no
     *
     * @param accountNo the value for jf_manage_account.account_no
     *
     * @mbggenerated Tue Aug 27 10:37:08 CST 2019
     */
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo == null ? null : accountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jf_manage_account.cre_company_no
     *
     * @return the value of jf_manage_account.cre_company_no
     *
     * @mbggenerated Tue Aug 27 10:37:08 CST 2019
     */
    public String getCreCompanyNo() {
        return creCompanyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jf_manage_account.cre_company_no
     *
     * @param creCompanyNo the value for jf_manage_account.cre_company_no
     *
     * @mbggenerated Tue Aug 27 10:37:08 CST 2019
     */
    public void setCreCompanyNo(String creCompanyNo) {
        this.creCompanyNo = creCompanyNo == null ? null : creCompanyNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jf_manage_account.account_name
     *
     * @return the value of jf_manage_account.account_name
     *
     * @mbggenerated Tue Aug 27 10:37:08 CST 2019
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jf_manage_account.account_name
     *
     * @param accountName the value for jf_manage_account.account_name
     *
     * @mbggenerated Tue Aug 27 10:37:08 CST 2019
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jf_manage_account.account_type
     *
     * @return the value of jf_manage_account.account_type
     *
     * @mbggenerated Tue Aug 27 10:37:08 CST 2019
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jf_manage_account.account_type
     *
     * @param accountType the value for jf_manage_account.account_type
     *
     * @mbggenerated Tue Aug 27 10:37:08 CST 2019
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType == null ? null : accountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jf_manage_account.remaining_amount
     *
     * @return the value of jf_manage_account.remaining_amount
     *
     * @mbggenerated Tue Aug 27 10:37:08 CST 2019
     */
    public BigDecimal getRemainingAmount() {
        return remainingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jf_manage_account.remaining_amount
     *
     * @param remainingAmount the value for jf_manage_account.remaining_amount
     *
     * @mbggenerated Tue Aug 27 10:37:08 CST 2019
     */
    public void setRemainingAmount(BigDecimal remainingAmount) {
        this.remainingAmount = remainingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jf_manage_account.status
     *
     * @return the value of jf_manage_account.status
     *
     * @mbggenerated Tue Aug 27 10:37:08 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jf_manage_account.status
     *
     * @param status the value for jf_manage_account.status
     *
     * @mbggenerated Tue Aug 27 10:37:08 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jf_manage_account.latest_trading_date
     *
     * @return the value of jf_manage_account.latest_trading_date
     *
     * @mbggenerated Tue Aug 27 10:37:08 CST 2019
     */
    public Date getLatestTradingDate() {
        return latestTradingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jf_manage_account.latest_trading_date
     *
     * @param latestTradingDate the value for jf_manage_account.latest_trading_date
     *
     * @mbggenerated Tue Aug 27 10:37:08 CST 2019
     */
    public void setLatestTradingDate(Date latestTradingDate) {
        this.latestTradingDate = latestTradingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jf_manage_account.latest_trading_no
     *
     * @return the value of jf_manage_account.latest_trading_no
     *
     * @mbggenerated Tue Aug 27 10:37:08 CST 2019
     */
    public String getLatestTradingNo() {
        return latestTradingNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jf_manage_account.latest_trading_no
     *
     * @param latestTradingNo the value for jf_manage_account.latest_trading_no
     *
     * @mbggenerated Tue Aug 27 10:37:08 CST 2019
     */
    public void setLatestTradingNo(String latestTradingNo) {
        this.latestTradingNo = latestTradingNo == null ? null : latestTradingNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jf_manage_account.latest_operator
     *
     * @return the value of jf_manage_account.latest_operator
     *
     * @mbggenerated Tue Aug 27 10:37:08 CST 2019
     */
    public String getLatestOperator() {
        return latestOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jf_manage_account.latest_operator
     *
     * @param latestOperator the value for jf_manage_account.latest_operator
     *
     * @mbggenerated Tue Aug 27 10:37:08 CST 2019
     */
    public void setLatestOperator(String latestOperator) {
        this.latestOperator = latestOperator == null ? null : latestOperator.trim();
    }

    public ManageAccount() {}

    public ManageAccount(String accountNo, String creCompanyNo, String accountName, String accountType, BigDecimal remainingAmount,
        String status, Date latestTradingDate, String latestTradingNo, String latestOperator) {
        super();
        this.accountNo = accountNo;
        this.creCompanyNo = creCompanyNo;
        this.accountName = accountName;
        this.accountType = accountType;
        this.remainingAmount = remainingAmount;
        this.status = status;
        this.latestTradingDate = latestTradingDate;
        this.latestTradingNo = latestTradingNo;
        this.latestOperator = latestOperator;
    }
    
}